title = "Tribalingua"
baseURL = "https://tribalingua.github.io/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

#  [[menu.header]]
#    weight = 3
#    name = "Blog"
#    url = "/blog"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"


  [params.slider]
    enable = true
    title = "Tribalingua"
    subtitle = "English language in-company classes"
    logo = "../img/logo.png"

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = ""
    paragraph = "Tribalingua provides English language classes in companies in Florianópolis.We work with most of the largest and best businesses on the island and mainland.All of our teachers are qualified and have considerable classroom experience.Our native speaker team uses gamification practices and interactive activities.Classes take place inside our client's premises and this means our students are able to study in their workplace.Groups are limited to 6 students maximum to increase speaking time and groups are levelled accordingly.We focus on a communicative approach with speaking and listening activities.Students are encouraged to interact and use the target language naturally.Preparation for international exams is also provided."   
    image = "../img/wrapper-img.png"
    

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content = "We understand that all students are different.Our classes are adapted according to learner needs, speaking and listening activities are used in the classroom to encourage production and communication.To achieve this we rely on interactive material and specific tasks.Our team always tries to connect education with realistic daily situations, with the focus on student speaking pratice.Themes are introduced according to both global and local news and topics."
    bgImage = "../img/feature-bg.jpg"
    [params.feature.button]
      caption = "View Works"
      url = "#"
      
  [params.call]
    enable = false
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
